### ISSUE TITLE
Transition to helm 3

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#1391]
Helm 2 has recently received its latest minor upgrade and will only receive potential security patches in the future (see [deprecation timeline](https://helm.sh/blog/#:~:text=Helm%20v2%20Deprecation%20Timeline&text=We%20recognize%20that%20rolling%20out,Helm%20v2%20until%20November%202020.). For us this means that we should transition to helm 3. I see the following steps:

- [x] Fix Renku charts to enable helm 3 deployments
- [x] Transition to using helm 3 for CI deployments and pipelines and our personal dev deployments
- [x] Migrate dev deployment to helm 3 (check if helm history can be preserved) use helm 3 in CD pipeline
- [x] Migrate production deployments to helm 3, adapt all documentation accordingly
- [ ] End support for helm 2 (which allows using new concepts which are not available in v1 charts)

**Comment by aledegano** [comment]
@ableuler in order to close this epic there is only the last point in the checklist. Do you think there is anything to do there?

**Comment by ableuler** [comment]
No, I think that was more a mental step than an actual action item :) Let's close this epic 🎉
