### ISSUE TITLE
Simplify use-cases which rely on a static Docker image

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#1611]
Many RenkuLab use-cases (ie courses, tutorials) do not benefit from the fact that an image for an interactive environment is built for every commit. In contrary, (superfluous) image builds are oftentimes just slowing down the user experience, for example after forking a project. For these use cases we should make it possible to pin an image which is available in any registry and simply use that image for the interactive environments. The necessary steps could be:

- [x] The notebook service should allow clients to specify image to be used when the image for the specific commit is missing (see https://github.com/swissdatasciencecenter/renku-notebooks/issues/304).
- [x] The UI should read the default image from the project configuration and include it in the post request ~when the image is not availble~ (see https://github.com/swissdatasciencecenter/renku-ui/issues/1105).
- [x] renku-python should allow to specify a default image for a project. This default image is added to the project configuration file.
- [ ] renku-python should allow the specification of a pinned image for a project. If one is provided, the `.gitlab-ci.yml`can be omitted and the pinned image is added to the project configuration file.
- [ ] The UI should include the additional project options for a default and a pinned image to the corresponding dialogue at project creation and potentially the project settings.
- [ ] The UI should adapt the image launch dialogue and omit the red sign indicative for a failure when the project configuration contains a pinned image to use.

**Comment by lorenzo-cavazzi** [comment]
I added a few issues to the epic.

I think point 4 or 5 should be handled with the project templates instead of adding any personalization to either renku-python or renku-ui. I'm not 100% sure I understand them correctly, but these are my thoughts:

4. renku-python already allows specifying an image in the project config file, it should just be documented properly (#1647 ). Omitting files should be part of specific templates. We may want to create a specific template as an example.
5. Any extra variable required at project creation to specify an image should be specified in a project template and it's already supported in the UI. We could add SwissDataScienceCenter/renku-ui#1114 to this epic (adjust settings from the UI) but I believe it's a generic UI improvement. Feel free to add it to this epic if you think it's especially important for the image.

**Comment by lorenzo-cavazzi** [comment]
I believe this epic can be closed unless we prefer to include the issue about adjusting the project settings in the UI SwissDataScienceCenter/renku-ui#1114

**Comment by rokroskar** [comment]
ping @ableuler - can we close this?

**Comment by ableuler** [comment]
I'd say so, yes. The original intent is met and whatever comes up subsequently is probably best addressed und a new epic.
