### ISSUE TITLE
improving the "first-steps" experience

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#186]
1) Prerequesistes 
  - [x] prerequisites need to be updated in the doc: (done in #251)
    - docker (tested with 18.03.0), must be running
    - sbt (I don't think this is needed anymore with container-only build?)
    - python3.6 (3.6.4 Anaconda, Inc)
    - pip (10.0.1)
2) System configuration
    - [x] document the `/etc/hosts` requirement (or just add this line to the `Makefile`?
    `grep -qi 'renga.build' /etc/hosts || sudo echo "127.0.0.1       keycloak.renga.build gitlab.renga.build renga.build jupyterhub.renga.build" >> /etc/hosts` (see https://github.com/SwissDataScienceCenter/renga/pull/174)

3) Wipe clean previous renga and all docker images
  - [x] document `make wipe` (done in #225)

5) Start renga
  - [x] document the use of `PLATFORM_VERSION` -- it must be set if the renga repo is on a branch that is different from the other component branches (done in #225)
  - [x] remove this message from `Makefile` (not needed anymore):
    "[Info] To make notebooks available as deployed environments, set the
            RENGA_NOTEBOOK_TOKEN and RENGA_REVIEW_DOMAIN CI variables in gitlab project settings."
        is not very helpful ... (done in #225)
  - [x] include pulling of alpine/git:latest (#207)

7) Renga user first steps:
 CLI:
    - [x] provide details (doc or online help) about --force https://github.com/SwissDataScienceCenter/renku-python/issues/199
    - [x] provide a more helpful message when the repo is dirty (fixed in https://github.com/SwissDataScienceCenter/renga-python/pull/160; also partially addressed by https://github.com/SwissDataScienceCenter/renga-python/issues/158)
    - [x] document the CLI (being done in https://github.com/SwissDataScienceCenter/renku-python/pull/191)
    ** ISSUE: could it be a problem that the commit message shows the full pathname of the command on the user's system? I can see the pros (e.g. better assist the user) and cons of having it vs not having it. However the cons may outweight the pros: this info will be shared and people may have an issue with that. --> actually I don't think this is a problem and the information may be critical for debugging problems with result reproducibility
     ~~simplify the commit message for `renga run`~~ (also see https://github.com/SwissDataScienceCenter/renga-python/issues/156)

```
$ renga dataset create dataset1
$ renga dataset add dataset1 'https://raw.githubusercontent.com/SwissDataScienceCenter/renga-python/development/README.rst'
$ renga run wc < data/dataset1/README.rst > wc_readme
$ renga log wc_readme
$ renga run grep 'SDSC' < data/dataset1/README.rst | wc > wc_sdsc_readme
```
This results in a dirty repo (?? wc_sdsc_readme), people will get stuck there

- [x]  better document what is allowed vs not allowed in the run command (https://github.com/SwissDataScienceCenter/renku-python/issues/179)

```
$ rm wc_sdsc_readme
$ renga run grep 'SDSC' < data/dataset1/README.rst > grep_readme
$ renga run wc -l < data/dataset1/README.rst > grep_readme
$ renga run grep -i 'SDSC' < data/dataset1/README.rst > grep_readme
```
      ... scary error message to just say that files has not changed.
- [x] simplify error message that tells you the outputs have not changed (https://github.com/SwissDataScienceCenter/renku-python/issues/164)

```
$ renga run grep -i 'Copyrights' < data/dataset1/README.rst > grep_readme
$ renga status
    On branch master
    Files generated from outdated inputs:
      (use "renga log <file>..." to see the full lineage)
        wc_grep_readme: grep_readme#0c90ef10
        Input files used in different versions:
        (use "renga log --revision <sha1> <file>" to see a lineage for the given revision)
            grep_readme: b2792a29, 0c90ef10
    > renga log wc_grep_readme
    *  90c54707 wc_grep_readme
    *  90c54707 .renga/workflow/5818ec18c8604e839d2f6e72a35d505d_wc.cwl
    *  0c90ef10 grep_readme
    *  0c90ef10 .renga/workflow/4318c07e8c424274b27d5c945c3a7f9d_grep.cwl
    @  7016db28 data/dataset1/README.rst
 ```
- [x] add `renga update` to the message about outdated results? (https://github.com/SwissDataScienceCenter/renku-python/issues/177)

 UI:
```
$ open renga.build
```
- [x] replace gitlab login with a renga login page (done in #187 but continued in #196)
- [x] provide a toy prepopulated project (e.g. the weather project), and step-by-step doc to import it in Renga via the gitlab interface. (see https://github.com/SwissDataScienceCenter/renga-demo) (see https://github.com/SwissDataScienceCenter/renga/pull/174)

A) GENERAL ISSUE:
- [x] remove notebooks from CLI until the CLI has a gitlab client
