### ISSUE TITLE
development --> master

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#215]
This issue is to keep track of work that needs to be done to transition from development to master. 

## Renaming (renga --> renku)

- [x] Docker hub -- create a new organization
- [x] Readthedocs -- new doc build (maybe this will happen automagically when we rename the repo??) @jirikuncar 
- [x] Readthedocs theme (change the character) @jirikuncar -> Renku: 連句 (http://tangorin.com/general/renku)
- [x] Travis-CI (make sure the builds run -- also might happen automatically when the repo is renamed)
- [ ] various renku URLs (renku.io, get-renku.io etc.) @erbou 
- [x] case-sensitive replace of renga --> renku in all the repositories (put links here with PRs)
   - [x] renga (@ableuler)
   - [x] renga-python (https://github.com/SwissDataScienceCenter/renku-python/pull/162)
   - [x] renga-storage (@ebiiii/@leafty) (SwissDataScienceCenter/renga-storage#62 SwissDataScienceCenter/renga-commons#26)
   - [x] renga-ui (@ableuler: SwissDataScienceCenter/renga-ui#206)
   - [x] proxy/gateway (@3C111: SwissDataScienceCenter/incubator-proxy/pull/5) 
   - [x] renga-demo (@ableuler: SwissDataScienceCenter/renga-demo#4)
   - [x] helm-charts (https://github.com/SwissDataScienceCenter/helm-charts/issues/1)
- [x] docker images (make sure all the repository names are changed in the builds)
- [x] CLI references (should mostly be handled by the above)
- [x] PyPI (@jirikuncar)
- [x] scala artifacts (@leafty)
- [x] references on datascience.ch (coordinate with Floriane - @erbou)

## Functionality

- [ ] improving first-steps: #186
- [ ] documentation
  - [ ] remove old unneeded parts
  - [ ] describe the current architecture
  - [ ] complete "first steps" including a demonstration of the UI

**Comment by jirikuncar** [comment]
Are we going to change the name at the same time?

**Comment by rokroskar** [comment]
That's the idea - most of the items on the list are about renaming

**Comment by leafty** [comment]
for docker images, use the `renku` org. e.g. `renku/renku-ui`
the access rights should be the same as the old `rengahub` org.
