### ISSUE TITLE
21 Jun Renku Tutorial preparation

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#235]
# Plan for day

The [tasks](#tasks) below are designed to support the follow plan.

## Morning (10.00 - 11.40)

Lecture covering the following:
- Introduction to Renku: Overview + Approach + Guidelines for use [Sekhar]
- Git flow refresher: work in branches, make MRs,  merge to master [Sandra]
- Introduction to the UI [Andreas]
- Introduction to the CLI [Jiri]
- Overview of technologies used in Renku: Gitlab, Docker, [JupyterHub?] [Rok]

## Afternoon

Lecture covering the following:
- Introduction to papermill [Jiri]
- Introduction to nbdime as a notebook diff tool [Sekhar]

Participants will be randomly assigned to teams (will try to have at least 1 from Lausanne and 1 from Zürich in each team). We will provide a zip file with data and code from https://www.crowdai.org/challenges/ieee-investment-ranking-challenge. There will be two forms of code, a package with some format readers, etc, and two (paper-mill-aware) notebooks that together constitute the base workflow. 

The participants will carry out the following tasks:
- Create a project in Renku (using the UI)
- Clone the project and add the data and code from the zip file
- Use renku run to construct the initial workflow
- Improve the notebooks in teams to get better results. Coordinate work using Kus, merging results, etc.

# <a name="tasks"></a>Tasks

- [x] Email preparation tasks to participants
  - Create an account on GitLab
  - Set up SSH key
- [x] define the project for the afternoon competition
- [ ] Tutorial UI issues (https://github.com/SwissDataScienceCenter/renku-ui/issues/222)
- [x] committing/pushing back notebooks (#261)
- [x] Dealing with branches and merge requests of notebooks in UI (https://github.com/SwissDataScienceCenter/renku-ui/issues/223)
 ~~Create mock-ups of possible branch/merge flows in the UI~~
- [x] Notebooks status page (in the notebooks service)
- [x] Creating custom environment images (start with repo2docker?) (#176)
- [x] Executing notebooks on the command line (via papermill)
- CD setup/debugging 
  - testing.datascience.ch
    - [x] creating projects
    - [x] pushing code via ssh
    - [x] launching notebooks
    - [x] image registry
    - [x] runners configured
  - working deployment for tutorial day
    - [x] creating projects
    - [x] pushing code via ssh
    - [x] launching notebooks
    - [x] image registry
    - [x] runners configured
- fix CLI issues
  - [x] path resolution on update (https://github.com/SwissDataScienceCenter/renku-python/issues/171)
  - [x] improve dirty repo handling (https://github.com/SwissDataScienceCenter/renku-python/issues/176)
  - [x] support `renku run` from a subdir (https://github.com/SwissDataScienceCenter/renku-python/pull/172)
- rework "first steps" in the docs (#251)
  - [x] CLI part
  - [x] UI part
  - [x] notebook?

**Comment by rokroskar** [comment]
tutorial done!
