### ISSUE TITLE
update developer/administrator documentation

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#289]
This is an umbrella issue for an overhaul of the developer/administrator documentation.

## To-do: 
- [x] remove references to old components
- [x] add new architecture diagrams
- [x] update sequence diagrams
### text/description update
- [x] notebooks
- [x] deployment (helm)

- [x] gitlab-ci
- [ ] UI

addresses #229

**Comment by rokroskar** [comment]
I think we've moved on...
