### ISSUE TITLE
how do we handle notebook launches in repos with lots of data in LFS?

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#343]
Current behavior is to pull all data from LFS on a notebook server launch (this happens inside one of the init containers). Instead, we should only pull in whatever data is actually in the dependency graph of the project at the current time. 

The consensus for now seems to be that the easiest implementation is to: 

- [x] do not pull LFS objects by default in the repo init container (https://github.com/SwissDataScienceCenter/renku-notebooks/pull/76)
- [x] provide docs that describe how to pull data you need by hand
- [x] make the renku cli do lazy pulling of LFS objects, e.g. on `update`, `rerun`
