### ISSUE TITLE
support interactive environment setup

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#443]
This is an umbrella issue to make it possible for users to configure the jupyter server that is launched for their project. 

The work spans at least the `renku-notebooks` and `renku-ui` repos: 

In notebooks:

- [x] provide a `/server_options` end point that lists the options the particular deployment can consume. This should be configurable through the chart. (https://github.com/SwissDataScienceCenter/renku-notebooks/pull/68)
- [x] accept `server_options` JSON as part of the `POST` request to `/notebooks/<namespace>/<project>/<commit-sha>`  (https://github.com/SwissDataScienceCenter/renku-notebooks/pull/68)

In the UI:

- [x] add "Launch Jupyter" to the "+" drop-down
- [x] create a new page for configuring the launch options
- [x] use `GET` with `application/json` to obtain information about the running notebook server at `/notebooks/<namespace>/<project>/<commit-sha>` and update the relevant buttons accordingly

~~move the page currently displayed under `Notebooks -> Launch Notebook Admin UI` to within the single-page app~~

**Comment by rokroskar** [comment]
The UI enhancement request lives on under https://github.com/SwissDataScienceCenter/renku-ui/issues/351
