### ISSUE TITLE
0.3.0 checklist

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#474]
Things to do before 0.3.0:

- [x] sync on which `renku-python` versions are being used and where (wait for v0.3.1)
- [x] review project template (https://github.com/SwissDataScienceCenter/renku-project-template/pull/14)
- [x] update version in the docs (https://github.com/SwissDataScienceCenter/renku/pull/480)
- [x] update chart dependencies (https://github.com/SwissDataScienceCenter/renku/pull/480)

Prepare release notes on:

- [x] renku
- [x] renku-ui (https://github.com/SwissDataScienceCenter/renku-ui/pull/356)
- [x] renku-gateway
- [x] renku-notebooks (https://github.com/SwissDataScienceCenter/renku-notebooks/pull/102)
- [x] renku-python (https://github.com/SwissDataScienceCenter/renku-python/pull/367)
- [x] renku-jupyter 

Tag and push images/charts for: 

- [x] renku-ui
- [x] renku-gateway
- [x] renku-notebooks
- [x] renku-python
- [x] renku-jupyter (https://github.com/SwissDataScienceCenter/renku-jupyter/pull/2) (wait for renku-python v0.3.1)
- [x] renku-demo (https://github.com/SwissDataScienceCenter/renku-demo/pull/23)

Tests:
- [x] test clean deployment using the published chart
- [ ] test upgrade

**Comment by rokroskar** [comment]
done a long time ago
