### ISSUE TITLE
prep new release

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#516]
Lots of usability/stability changes have been made to various components -- lets make a 0.3.1 release of the renku chart that will include updates from the gateway, the UI and renku-python. Please tag whatever the last stable version of the component you're responsible for *before* the graph integration. I'll do the main `renku` repo last to include all the tagged versions. 

- [x] renku
- [x] renku-ui [pull request](https://github.com/SwissDataScienceCenter/renku-ui/pull/386)
- [x] renku-gateway
- [x] renku-python
- [x] renku-jupyter [milestone](https://github.com/SwissDataScienceCenter/renku-jupyter/milestone/1) [pr](https://github.com/SwissDataScienceCenter/renku-jupyter/pull/20)
- [x] renku-notebooks [milestone](https://github.com/SwissDataScienceCenter/renku-notebooks/milestone/2) [pr](https://github.com/SwissDataScienceCenter/renku-notebooks/pull/113)
- [x] renku-project-template [milestone](https://github.com/SwissDataScienceCenter/renku-project-template/milestone/2)

**Comment by rokroskar** [comment]
Done!
