### ISSUE TITLE
prep new release

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#603]
Lots of updates to various services, time for a new release:

- [x] release renku-ui
- [x] release renku-graph
- [x] release renku-gateway
- [x] release renku-python
- [x] release renku-notebooks
- [x] update base images
- [ ] release renku with correct `requirements.yaml` and `requirements.lock`
- [x] update project templates 
- [x] test deploy the final chart
