### ISSUE TITLE
QA for the renku project

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku#726]
This epic is for the QA strategy for testing renkulab and renku.

**Ad Hoc QA**
- [x] QA confluence page to document what tests have been run for a candidate deployment: https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/111968257/QA
- [x] Project built by each person on the team that lives in `renku-qa` group (see below)

**QA organization**
- [x] QA group for projects: the `renku-qa` group on `dev` to put the QA projects.
- [x] Template for QA projects ("requirements" for QA, docs for "how to QA")
- [ ] Process/requirements for adding manual tests to automated tests
- [ ] agreed upon setup to develop QA: i.e. stable.dev.renku.ch, which should match the deployment on renku (should only differ preceding a new deployment so that the new deployment can be tested; otherwise use for debugging/verifying robustness of current deploy (?))

**QA Coverage**
- [x] check how much data can be accommodated in a project
- [ ] integration of components (e.g. project creation uses correct template; notebook can be spawned and shut down; etc.)
- [ ] Automated QA for features initially tested manually projects have been created (Selenium and helm)

**Comment by rokroskar** [comment]
I believe most of the things here have been put in place.
