### ISSUE TITLE
build: migrate CI to github actions

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#783]
We would like to consolidate the CI for the whole project into github actions so we can reuse pieces across the different repositories. 

To-do: 

- [x] create a re-usable action to update the component version in the main renku repo (#784)
- [x] migrate renku-graph (https://github.com/SwissDataScienceCenter/renku-graph/issues/251)
- [x] update renku-core using the docker action
- [x] migrate notebooks
- [x] migrate gateway
- [x] migrate UI

**Comment by rokroskar** [comment]
all done
